name: 'Create commit'

description: |
  Stages the given pathspec and creates a git commit with the given message.
  This action will fail if there are no changes or if pathspec doesn't exist/is
  invalid.

inputs:
  message:
    description: 'Commit message'
    required: true
  pathspec:
    description: 'Git pathspec to stage'
    required: true
  committer_name:
    description: 'Name of the committer'
    required: false
    default: 'paketo-bot'
  committer_email:
    description: 'Email of the committer'
    required: false
    default: 'paketobuildpacks@gmail.com'
  keyid:
    description: 'ID of GPG signing key to use for signed commit'
    required: false
    default: ''
  key:
    description: 'GPG signing key to use for signed commit'
    required: false
    default: ''

outputs:
  commit_sha:
    description: 'The sha of the commit'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--message"
  - ${{ inputs.message }}
  - "--pathspec"
  - ${{ inputs.pathspec }}
  - "--committer-name"
  - ${{ inputs.committer_name }}
  - "--committer-email"
  - ${{ inputs.committer_email }}
  - "--keyid"
  - ${{ inputs.keyid }}
  - "--key"
  - ${{ inputs.key }}
