#!/bin/bash

set -eu
set -o pipefail

function main() {
  local message pathspec keyid key
  while [ "${#}" != 0 ]; do
    case "${1}" in
      --message)
        message="${2}"
        shift 2
        ;;

      --pathspec)
        pathspec="${2}"
        shift 2
        ;;

      --keyid)
        keyid="${2}"
        shift 2
        ;;

      --key)
        key="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  if [ -n "$keyid" ] && [ -n "$key" ]; then
    mkdir -p ~/.gnupg/
    printf "quiet" > ~/.gnupg/options
    printf "%s" "$key" | base64 -d > ~/.gnupg/private.key
    gpg --options ~/.gnupg/options --import ~/.gnupg/private.key

    git config --global user.signingkey "$keyid"
    git config --global commit.gpgsign true
  fi

  git config --global user.email "paketobuildpacks@gmail.com"
  git config --global user.name "paketo-bot"

  if [[ -n "$(git status --short -- "${pathspec}")" ]]; then
    git add --all "${pathspec}"
    git commit --message "${message}"

    echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
    exit 0
  fi
}

main "${@:-}"
