#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function main() {
  local token repo

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --token)
        token="${2}"
        shift 2
        ;;

      --repo)
        repo="${2}"
        shift 2
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  if [[ -z "${token}" ]]; then
    echo "--token is a required flag"
    exit 1
  fi

  if [[ -z "${repo}" ]]; then
    echo "--repo is a required flag"
    exit 1
  fi

  local version
  version="$(
    curl "https://api.github.com/repos/${repo}/releases/latest" \
      --fail-with-body \
      --show-error \
      --header "Authorization: token ${token}" \
      --silent \
      --location \
    | jq -r -S .tag_name
  )"

  echo "::set-output name=version::${version}"
}

main "${@:-}"
