version: 2
updates:
- package-ecosystem: gomod
  directory: "/actions/dispatch/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/pull-request/download-artifact/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/release/create/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/release/reset-draft/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/dependency/update-metadata-json/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/release/download-asset/entrypoint/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/stack/diff-package-receipts/entrypoint/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/stack/get-usns/entrypoint/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/stack/release-notes/entrypoint/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "actions/tag/calculate-semver/entrypoint/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "scripts/publish_draft_releases/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/builder"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/implementation"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/language-family"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/library"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/stack"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
