version: 2
updates:
- package-ecosystem: gomod
  directory: "/actions/dispatch/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/pull-request/download-artifact/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/release/create/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/actions/release/reset-draft/entrypoint"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/builder"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/implementation"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/language-family"
  schedule:
    interval: daily
