module.exports = {
    username: 'paketo-bot',
    gitAuthor: 'paketo-bot <paketobuildpacks@gmail.com>',
    onboarding: false,
    platform: 'github',
    forkProcessing: 'enabled',
    repositories: [
        "paketo-buildpacks/occam",
        "paketo-buildpacks/github-config",
        "paketo-buildpacks/cpython",
        "paketo-buildpacks/libnodejs",
        "paketo-buildpacks/node-engine",
        "paketo-buildpacks/node-start",
        "paketo-buildpacks/npm-install",
        "paketo-buildpacks/yarn",
        "paketo-buildpacks/yarn-start",
        "paketo-buildpacks/yarn-install",
        "paketo-buildpacks/ubi-nodejs-extension",
        "paketo-buildpacks/node-run-script",
    ],
}
