name: 'Diff Package Receipts'

description: 'Given two package receipts as text files, produce list of added and removed packages'
inputs:
  previous:
    description: 'Path to previous package receipt'
    required: true
  current:
    description: 'Path to current package receipt'
    required: true
  added_diff_file:
    description: 'List of packages added'
    required: true
  removed_diff_file:
    description: 'List of packages removed'
    required: true
  modified_diff_file:
    description: 'List of packages modified'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--previous"
  - "${{ inputs.previous }}"
  - "--current"
  - "${{ inputs.current }}"
  - "--added-diff-file"
  - "${{ inputs.added_diff_file }}"
  - "--removed-diff-file"
  - "${{ inputs.removed_diff_file }}"
  - "--modified-diff-file"
  - "${{ inputs.modified_diff_file }}"
