name: 'Generate Builder.toml'

description: |
  This action updates the builder.toml with any new dependency versions.

inputs:
  token:
    description: 'Github Access Token used to make the request'
    required: true

runs:
  using: 'composite'
  steps:

  - name: Choose Jam Version
    id: version
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      version="$(
        curl "https://api.github.com/repos/paketo-buildpacks/jam/releases/latest" \
          --fail-with-body \
          --show-error \
          --header "Authorization: token ${{ inputs.token }}" \
          --location \
          --silent \
        | jq -r -S .tag_name
      )"
      echo "version=${version#v}" >> "$GITHUB_OUTPUT"

  - name: Install Jam
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      mkdir -p "${HOME}"/bin
      echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
      mkdir -p "${HOME}/bin"
      curl "https://github.com/paketo-buildpacks/jam/releases/download/v${{ steps.version.outputs.version }}/jam-linux" \
        --fail-with-body \
        --show-error \
        --silent \
        --location \
        --output "${HOME}/bin/jam"
      chmod +x "${HOME}/bin/jam"

  - name: Update Builder
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      jam update-builder \
        --builder-file "${PWD}/builder.toml"
