name: 'Generate Builder.toml'

description: |
  This action updates the builder.toml with any new dependency versions.

runs:
  using: 'composite'
  steps:

  - name: Choose Jam Version
    id: version
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      version="$(
        curl "https://api.github.com/repos/paketo-buildpacks/jam/releases/latest" \
          --header "Authorization: token ${GITHUB_TOKEN}" \
          --location \
          --silent \
        | jq -r -S .tag_name
      )"
      echo "::set-output name=version::${version#v}"

  - name: Install Jam
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      mkdir -p "${HOME}"/bin
      echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
      mkdir -p "${HOME}/bin"
      curl "https://github.com/paketo-buildpacks/jam/releases/download/v${{ steps.version.outputs.version }}/jam-linux" \
        --silent \
        --location \
        --output "${HOME}/bin/jam"
      chmod +x "${HOME}/bin/jam"

  - name: Update Builder
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      jam update-builder \
        --builder-file "${PWD}/builder.toml"
