name: 'Push branch'

description: |
  Push a git branch to the remote "origin"

inputs:
  branch:
    description: 'Name of the branch to push'
    required: true
  force:
    description: 'Push using --force-with-lease'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--branch"
  - ${{ inputs.branch }}
  - "--force"
  - ${{ inputs.force }}
