#!/bin/bash
set -euo pipefail
shopt -s inherit_errexit

function main() {
  local branch force
  while [ "${#}" != 0 ]; do
    case "${1}" in
      --branch)
        branch="${2}"
        shift 2
        ;;

      --force)
        force="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  git config --global --add safe.directory "${GITHUB_WORKSPACE}"

  if [[ "${force}" == "true" ]]; then
    git push origin "${branch}" --force-with-lease
  else
    git push origin "${branch}"
  fi
}

main "${@:-}"
