name: 'Tag'

description: |
  Tags the repository with the next highest patch number given an existing tag.

inputs:
  current_version:
    description: 'If set will override script and use this version as the tag'
  allow_head_tagged:
    description: 'If set to "true", allow re-tagging a git commit that already has a tag'
    required: false
    default: 'false'

outputs:
  tag:
    description: 'Tag produced from the action'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --current-version
  - ${{ inputs.current_version }}
  - --allow-head-tagged
  - ${{ inputs.allow_head_tagged }}
