#!/usr/bin/env sh

set -e
set -u

download_url=
tag=

main() {
  download_url="$(jq -r '.release.assets[] | select(.name | endswith(".cnb")) | .url' "${GITHUB_EVENT_PATH}")"
  tag="$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}")"

  curl "${download_url}" \
    --header "Authorization: token ${GITHUB_TOKEN}" \
    --header "Accept: application/octet-stream" \
    --silent \
    --location \
    --output "${GITHUB_WORKSPACE}/buildpackage.cnb"

  echo "::set-output name=buildpackage::buildpackage.cnb"
  echo "::set-output name=tag::${tag#v}"
}

main "${@:-}"
