name: 'Generate Builder.toml'

description: |
  This action generates a builder.toml[1] given an order.toml, stack id and
  stack images. All buildpack images, lifecycle-image and build-image are
  tagged with their exact latest versions in the generated builder.toml, but
  the run-image and run-image-mirrors are tagged with the provided
  stack-image-tag
  [1] https://buildpacks.io/docs/reference/config/builder-config

# It is assumed that ${registry-server}/<buildpack-id> gives the name of the
# buildpack image. When this assumption is not valid anymore, this action will
# require to implement an {id, image} mapping.
inputs:
  stack:
    description: 'ID of the stack to use for the builder'
    required: true
  build-image:
    description: 'Build Image'
    required: true
  run-image:
    description: 'Run Image'
    required: true
  run-image-mirrors:
    description: 'Comma separated list of Run Image Mirrors'
    required: true
  stack-image-tag:
    description: 'Specific image tag for build image, run image, and run image mirrors'
    required: true
  order-file:
    description: 'Path to the order.toml file'
    required: true
  registry-server:
    description: 'Registry server uri for images in order.toml (.e.g. gcr.io)'
    required: true

outputs:
  builder_toml:
    description: The generated builder.toml for the builder

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--order-file"
  - ${{ inputs.order-file }}
  - "--registry-server"
  - ${{ inputs.registry-server }}
  - "--stack"
  - ${{ inputs.stack }}
  - "--build-image"
  - ${{ inputs.build-image }}
  - "--run-image"
  - ${{ inputs.run-image }}
  - "--run-image-mirrors"
  - ${{ inputs.run-image-mirrors }}
  - "--stack-image-tag"
  - ${{ inputs.stack-image-tag }}
