#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

function main() {
  local repo all
  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --repo)
        repo="${2}"
        shift 2
        ;;

      --all)
        all="${2}"
        shift 2
        ;;

      "")
        # skip if the argument is empty
        shift 1
        ;;

      *)
        echo "Unknown argument" "$@"
        exit 1
    esac
  done

  if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "Must set \$GITHUB_TOKEN"
    exit 1
  fi

  gh auth status

  # Publish the highest semver release as "latest":
  # get all draft releases
  # trim off the 'v' prefix in the version
  # separates each part of the version
  # sorts versions in ascending order
  # readd the 'v' prefix to each version (needed for gh CLI to find the release correctly)

  versions=$(gh api /repos/${repo}/releases | jq -r '[.[] | select(.draft == true) | .tag_name] | map(ltrimstr("v")) | sort_by( split(".") | map(tonumber) ) | map("v" + .)')

  if [[ $(jq length <<<"$versions") -eq 0 ]]; then
    echo "Nothing to release!"
  else
    if [[ "${all}" == "true" ]]; then
      # publish ALL draft releases, in order of lowest semantic version to highest
      for release in $(echo ${versions} | jq -r .[]); do
        publish "${release}" "${repo}"
      done
    else
      # publish the LAST element in the version list
      # this corresponds to the HIGHEST semver version
      release=$(echo ${versions} | jq -r .[-1])
      publish "${release}" "${repo}"
    fi
  fi
}

function publish() {
  local release repo
  release="${1}"
  repo="${2}"

  echo "Publishing ${release} for ${repo}"
  gh release edit ${release} -R ${repo} --draft=false
}

main "${@:-}"

