name: 'Check PR'

description: |
  Checks whether PRs have been modified by human user accounts.

inputs:
  token:
    description: 'Token used to authenticate user account'
    required: true
  repo:
    description: 'Github repository'
    required: true
  number:
    description: 'PR number'
    required: true
  bots:
    description: 'A comma-separated list of bot usernames from which to allow commits.'
    required: true
    default: 'dependabot[bot],web-flow,paketo-bot,cf-buildpacks-eng'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--token"
  - ${{ inputs.token }}
  - "--repo"
  - ${{ inputs.repo }}
  - "--number"
  - ${{ inputs.number }}
  - "--bots"
  - ${{ inputs.bots }}
