name: 'Modify metadata.json'

description: |
  Modifies a metadata.json file entry with checksum and URI fields, given an
  entry in the file matches the version and target.

inputs:
  version:
    description: 'dependency version'
    required: true
  target:
    description: 'dependency OS target variant'
    required: true
  checksum:
    description: 'dependency checksum to add'
    required: true
  uri:
    description: 'dependency URI to add'
    required: true
  file:
    description: 'metadata file to modify'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--version"
  - ${{ inputs.version }}
  - "--target"
  - ${{ inputs.target }}
  - "--checksum"
  - ${{ inputs.checksum }}
  - "--uri"
  - ${{ inputs.uri }}
  - "--file"
  - ${{ inputs.file }}
