name: 'Create Buildpack Repo Release Notes'

description: |
  Creates release notes for a buildpack repo

inputs:
  repo:
    description: 'Repository to create draft release'
    required: true
  token:
    description: 'Github Access Token used to make the request'
    required: true
  buildpackage_path:
    description: 'Relative path to the .cnb buildpackage'
    default: 'build/buildpackage.cnb'
  buildpack_type:
    description: 'Specifies whether it is a buildpack or an extension'
    default: 'buildpack'

outputs:
  release_body:
    description: Generated detailed release notes for the buildpack repo

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--repo"
  - ${{ inputs.repo }}
  - "--token"
  - ${{ inputs.token }}
  - "--buildpackage-path"
  - ${{ inputs.buildpackage_path }}
  - "--buildpack-type"
  - ${{ inputs.buildpack_type }}
