name: 'Create Language Family Release Notes'

description: |
  Creates release notes for a language family

inputs:
  repo:
    description: 'Repository that will have draft release reset'
    required: true
  token:
    description: 'Github Access Token used to make the request'
    required: true

outputs:
  release_body:
    description: Generated detailed release notes for the language family

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--repo"
  - ${{ inputs.repo }}
  - "--token"
  - ${{ inputs.token }}
