#!/bin/bash

function main() {
  local content
  content="$(
    jam summarize \
      --buildpack "${GITHUB_WORKSPACE}/build/buildpackage.cnb" \
      --format markdown
  )"

  # Convert multiline output to single line output as GitHub "set-output" does
  # not support multiline strings:
  # https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/m-p/38372#M3322
  content="${content//'%'/'%25'}"
  content="${content//$'\n'/'%0A'}"
  content="${content//$'\r'/'%0D'}"

  echo "::set-output name=release_body::${content}"
}

main "${@:-}"
