name: 'Tag Docs Submodule'

description: |
  Tags the repository with docs/v${version} given a $version.

inputs:
  version:
    description: 'The numeric version with which to tag the docs submodule'
    required: true

outputs:
  tag:
    description: 'Tag produced from the action'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --version
  - ${{ inputs.version }}
