name: 'Create Stack'

description: |
  Creates a stack in a provided repository, including any provided secrets.

inputs:
  secrets:
    description: Secrets provided in the form key=value. Separated by whitespace (including newlines).
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--secrets"
  - ${{ inputs.secrets }}
