name: 'Update buildpack.toml with new buildpack versions'

description: |
  This action updates the buildpack.toml with any new buildpack versions.

inputs:
  buildpack_toml_path:
    description: 'Relative path to buildpack.toml'
    default: 'buildpack.toml'
  package_toml_path:
    description: 'Relative path to package.toml'
    default: 'package.toml'
  no_cnb_registry:
    description: 'Turn off using CNB registry URIs in package.toml'
    default: 'false'
  patch_only:
    description: 'Allow only buildpack patch updates'
    default: 'false'

outputs:
  semver_bump:
    description: 'The highest semver bump across all updated dependencies in the buildpack.toml'
    value: ${{ steps.update.outputs.semver_bump }}

runs:
  using: 'composite'
  steps:

  - name: Choose Jam Version
    id: version
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      version=$(jq -r .jam "scripts/.util/tools.json")
      echo "version=${version#v}" >> "$GITHUB_OUTPUT"

  - name: Install Jam
    id: install
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      mkdir -p "${HOME}"/bin
      echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
      mkdir -p "${HOME}/bin"
      curl "https://github.com/paketo-buildpacks/jam/releases/download/v${{ steps.version.outputs.version }}/jam-linux" \
        --fail-with-body \
        --show-error \
        --silent \
        --location \
        --output "${HOME}/bin/jam"
      chmod +x "${HOME}/bin/jam"

  - name: Update Buildpack
    id: update
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit

      output="$(jam update-buildpack \
        --buildpack-file "${PWD}/${{ inputs.buildpack_toml_path }}" \
        --package-file "${PWD}/${{ inputs.package_toml_path }}" \
        --no-cnb-registry="${{ inputs.no_cnb_registry }}" \
        --patch-only="${{ inputs.patch_only }}" )"

      # output looks like: 'Highest semver bump: <patch|minor|major|<none>>'
      semver_bump=$(echo "${output}" | cut -d' ' -f4)
      echo "semver_bump=${semver_bump}"
      echo "semver_bump=${semver_bump}" >> "$GITHUB_OUTPUT"
