name: 'Get Stack USNs'

description: |
  Gets list of new USNs for the stack given a list of relevant packages
  and a list of last-known USNs.

outputs:
  usns:
    description: JSON array of patched USNs or path to JSON file, if usns_output_path flag is specified

inputs:
  last_usns:
    description: 'JSON array of last known USNs'
    required: false
    default: '[]'
  last_usns_filepath:
    description: 'Similar to last_usns, but instead of pointing into a variable, it points to a file'
    required: false
  packages:
    description: 'JSON array of stack package names'
    required: false
    default: '[]'
  packages_filepath:
    description: 'Similar to packages, but instead of pointing into a variables, it points to a file'
    required: false
  distribution:
    description: 'Ubuntu distribution of stack (bionic|focal|jammy|noble)'
    required: true
  usns_output_path:
    description: 'Path to output usns JSON file'
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/paketo-buildpacks/actions/stack/get-usns:latest'
  args:
  - "--last-usns"
  - "${{ inputs.last_usns }}"
  - "--last-usns-filepath"
  - "${{ inputs.last_usns_filepath }}"
  - "--packages"
  - "${{ inputs.packages }}"
  - "--packages-filepath"
  - "${{ inputs.packages_filepath }}"
  - "--distro"
  - "${{ inputs.distribution }}"
  - "--output"
  - "${{ inputs.usns_output_path }}"
