name: "Update Go Mod Version"
description: |
  Updates the versions of go and the go toolchain in a go.mod file

inputs:
  go-version:
    description: 'Version of go to write for both the go version and the toolchain version'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--go-version"
  - "${{ inputs.go-version }}"
