#! /usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

function main() {
  local go_version
  go_version=""

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --go-version)
        go_version="${2}"
        shift 2
        ;;

      "")
        # skip if the argument is empty
        shift 1
        ;;

      *)
        echo "Unknown argument" "$@"
        exit 1
    esac
  done
  
  if [[ -z "${go_version}" ]]; then
    echo "Must provide go version"
    exit 1
  fi

  local -a go_mod_files
  go_mod_files=("go.mod" "dependency/retrieval/go.mod")

  echo "Setting go version to: '${go_version}'"

  for go_mod_file in "${go_mod_files[@]}"; do
    if [[ ! -f "${go_mod_file}" ]]; then
      continue
    fi

    sed -i "s/^go .*/go ${go_version}/g" "${go_mod_file}"
  done
}

main "${@:-}"

