#! /usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

function main() {
  local go_version
  go_version=""

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --go-version)
        go_version="${2}"
        shift 2
        ;;

      "")
        # skip if the argument is empty
        shift 1
        ;;

      *)
        echo "Unknown argument" "$@"
        exit 1
    esac
  done
  
  if [[ -z "${go_version}" ]]; then
    echo "Must provide go version"
    exit 1
  fi

  echo "Setting go version to: '${go_version}'"
  sed -i "s/go .*/go ${go_version}/g" go.mod

  echo "setting toolchain to: '${go_version}'"
  if grep -qE 'toolchain go(.*)' < go.mod; then 
    sed -i "s/toolchain go.*/toolchain go${go_version}/g" go.mod
  else
    # Write the toolchain directive two lines below the go version
    sed -i "/go ${go_version}/r"<(printf "\ntoolchain go%s\n" "${go_version}") go.mod
  fi
}

main "${@:-}"

