name: 'Sync'

description: |
  Syncs directories between a shared github-config repo and a buildpack repo

inputs:
  workspace:
    description: 'Path to the workspace to sync into'
    required: true

  config:
    description: 'Path to the github-config directory to sync'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --workspace
  - ${{ inputs.workspace }}
  - --config
  - ${{ inputs.config }}
