#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

function main() {
  local workspace config

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --workspace)
        workspace="${2}"
        shift 2
        ;;

      --config)
        config="${2}"
        shift 2
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  pushd "${config}" > /dev/null
    IFS=" " read -r -a directories < <(find . -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0)
  popd > /dev/null

  for dir in "${directories[@]}"; do
    local src dest
    src="$(cd "${config}/${dir}" && pwd)/"
    dest="$(cd "${workspace}/${dir}" && pwd)/"

    echo "syncing from ${src} to ${dest}"

    local args=(
      --recursive
      -vv
      --checksum
      "${src}"
      "${dest}"
      --delete
    )

    if [[ -f "${dest}/.syncignore" ]]; then
      args+=(
        --exclude=".syncignore"
        --exclude-from="${dest}/.syncignore"
      )
    fi

    bash -c "rsync ${args[*]}"

    echo
  done
}

main "${@:-}"
