#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function main() {
  local workspace config

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --workspace)
        workspace="${2}"
        shift 2
        ;;

      --config)
        config="${2}"
        shift 2
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  pushd "${config}" > /dev/null
    IFS=" " read -r -a directories < <(find . -type d -depth 1 -print0 | xargs -0)
  popd > /dev/null

  for dir in "${directories[@]}"; do
    local src dest
    src="$( cd "${config}/${dir}" && pwd)/"
    dest="$(cd "${workspace}/${dir}" && pwd)/"

    echo "syncing from ${src} to ${dest}"

    if [[ -f "${dest}/.syncignore" ]]; then
      rsync \
        -r -v -c "${src}" \
        "${dest}" \
        --delete \
        --exclude=".syncignore" \
        --exclude-from="${dest}/.syncignore"
    else
      rsync \
        -r -v -c "${src}" \
        "${dest}" \
        --delete
    fi

    echo
  done
}

main "${@:-}"
