name: 'Create Release Notes'

description: |
  Creates release notes for a stack in Markdown format

outputs:
  release_body:
    description: Generated detailed release notes for the stack

inputs:
  build_image:
    description: 'Image registry location of build image'
    required: true
  run_image:
    description: 'Image registry location of run image'
    required: true
  build_cve_report:
    description: 'CVE scan report path of build image in markdown format'
    required: false
  run_cve_report:
    description: 'CVE scan report path of run image in markdown format'
    required: false
  build_packages_added:
    description: 'Path to build packages added file'
    required: false
  build_packages_modified:
    description: 'Path to build packages modified file'
    required: false
  build_packages_removed_with_force:
    description: 'Path to build packages removed file'
    required: false
  run_packages_added:
    description: 'Path to run packages added file'
    required: false
  run_packages_modified:
    description: 'Path to run packages modified file'
    required: false
  run_packages_removed_with_force:
    description: 'Path to run packages removed file'
    required: false
  patched_usns:
    description: 'JSON array of objects "{ name: USN name, url: USN URL, description: USN description}"'
    required: false
  supports_usns:
    description: 'Boolean whether the release notes should support/show USNs'
    required: false
  receipts_show_limit:
    description: 'Integer which defines the limit of whether it should show or not the receipts array of each image'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--build-image"
  - "${{ inputs.build_image }}"
  - "--run-image"
  - "${{ inputs.run_image }}"
  - "--build-cve-report"
  - "${{ inputs.build_cve_report }}"
  - "--run-cve-report"
  - "${{ inputs.run_cve_report }}"
  - "--patched-usns"
  - "${{ inputs.patched_usns }}"
  - "--build-added"
  - "${{ inputs.build_packages_added }}"
  - "--build-modified"
  - "${{ inputs.build_packages_modified }}"
  - "--build-removed"
  - "${{ inputs.build_packages_removed_with_force }}"
  - "--run-added"
  - "${{ inputs.run_packages_added }}"
  - "--run-modified"
  - "${{ inputs.run_packages_modified }}"
  - "--run-removed"
  - "${{ inputs.run_packages_removed_with_force }}"
  - "--supports-usns"
  - "${{ inputs.supports_usns }}"
  - "--receipts-show-limit"
  - "${{ inputs.receipts_show_limit }}"
