name: 'Download artifact'

description: |
  Downloads the event payload artifact associated with
  a workflow run.

inputs:
  name:
    description: 'Name of the uploaded artifact'
    required: true
  repo:
    description: 'Org and repository that the workflow lives in'
    required: true
  run_id:
    description: 'ID of the specific workflow that contains the artifact'
    required: true
  github_api:
    description: 'Github API endpoint to query for the download'
    required: false
    default: "https://api.github.com"
  workspace:
    description: 'Path to the workspace to put artifacts'
    required: true
  token:
    description: 'Github Access Token used to make the request'
    required: true


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--name"
  - ${{ inputs.name }}
  - "--repo"
  - ${{ inputs.repo }}
  - "--run-id"
  - ${{ inputs.run_id }}
  - "--github-api"
  - ${{ inputs.github_api }}
  - "--workspace"
  - ${{ inputs.workspace }}
  - "--token"
  - ${{ inputs.token }}
