#!/usr/bin/env bash

set -eu
set -o pipefail

function main() {
  local url output token

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --url)
        url="${2}"
        shift 2
        ;;

      --output)
        output="${2}"
        shift 2
        ;;

      --token)
        token="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done


  mkdir -p "$(dirname "${output}")"

  echo "Downloading ${url}"
  curl "${url}" \
    --fail-with-body \
    --show-error \
    --header "Authorization: token ${token}" \
    --header "Accept: application/octet-stream" \
    --silent \
    --location \
    --output "${output}"

  echo "Asset downloaded to ${output}"
}

main "${@:-}"
