# Requirement:
# Mergify app must be installed at the target repository
# See github.com/<org>/<repo>/settings/installations

pull_request_rules:
  - name: Auto merge pull requests from github-actions bot
    conditions:
      - author=github-actions[bot]
      - status-success=Unit Tests
      - status-success=Integration Tests
    actions:
      merge:
        strict: true
        method: rebase
      delete_head_branch: {}

  - name: Auto merge pull requests from paketo-bot user
    conditions:
      - author=paketo-bot
      - status-success=Unit Tests
      - status-success=Integration Tests
    actions:
      merge:
        strict: true
        method: rebase
      delete_head_branch: {}

  - name: Auto merge pull requests from Dependabot bot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Unit Tests
      - status-success=Integration Tests
    actions:
      merge:
        strict: true
        method: rebase
      delete_head_branch: {}
