name: 'Generate Package List'
description: 'Generates a list of packages (without versions) given a dpkg -l style package receipt'
inputs:
  build_receipt:
    description: 'Package receipt for build image'
    required: true
  run_receipt:
    description: 'Package receipt for run image'
    required: true
  output_path:
    description: 'Path where asset should be downloaded'
    required: false

outputs:
  packages:
    description: 'JSON array of packages contained in build and run images. Empty if output_path is provided as input'
    value: ${{ steps.packages.outputs.packages }}
  output_path:
    description: 'Absolute path to the downloaded artifact. Empty if no output_path as input is provided'
    value: ${{ steps.packages.outputs.output_path }}

runs:
  using: 'composite'
  steps:
  - id: packages
    shell: bash
    run: |
      if [[ -n "${{ inputs.output_path }}" ]]; then
        result=$("${{ github.action_path }}/generate-package-list.sh" \
          --build-receipt "${{ inputs.build_receipt }}" \
          --run-receipt "${{ inputs.run_receipt }}" \
          --output "${{ inputs.output_path }}")
        printf "output_path=%s\n" "${result}" >> "$GITHUB_OUTPUT"
      else
        result=$("${{ github.action_path }}/generate-package-list.sh" \
          --build-receipt "${{ inputs.build_receipt }}" \
          --run-receipt "${{ inputs.run_receipt }}")
        printf "packages=%s\n" "${result}" >> "$GITHUB_OUTPUT"
      fi
