name: 'Rebase branch'

description: |
  Rebases a branch against the base branch

inputs:
  base_branch:
    description: 'Name of the base branch to rebase onto (the current branch is rebased on top of this branch)'
    required: false
    default: 'main'
  committer_name:
    description: 'Name of the committer'
    required: false
    default: 'paketo-bot'
  committer_email:
    description: 'Email of the committer'
    required: false
    default: 'paketobuildpacks@gmail.com'
  keyid:
    description: 'ID of GPG signing key to use for signed commit'
    required: false
    default: ''
  key:
    description: 'GPG signing key to use for signed commit'
    required: false
    default: ''
  fail_on_rebase_failure:
    description: 'If true, the step fails when the rebase fails (e.g. conflicts)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Rebase branch
      shell: bash
      run: |
        bash "${{ github.action_path }}/entrypoint" \
          --base-branch "${{ inputs.base_branch }}" \
          --committer-name "${{ inputs.committer_name }}" \
          --committer-email "${{ inputs.committer_email }}" \
          --keyid "${{ inputs.keyid }}" \
          --key "${{ inputs.key }}" \
          --fail-on-rebase-failure "${{ inputs.fail_on_rebase_failure }}"
