name: 'Update buildpack.toml with new dependencies'

description: |
  This action updates the buildpack.toml with any new dependency versions.

runs:
  using: 'composite'
  steps:

  - name: Choose Jam Version
    id: version
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      version=$(jq -r .jam "scripts/.util/tools.json")
      echo "::set-output name=version::${version#v}"

  - name: Install Jam
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      mkdir -p "${HOME}"/bin
      echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
      mkdir -p "${HOME}/bin"
      curl "https://github.com/paketo-buildpacks/jam/releases/download/v${{ steps.version.outputs.version }}/jam-linux" \
        --silent \
        --location \
        --output "${HOME}/bin/jam"
      chmod +x "${HOME}/bin/jam"

  - name: Update Dependencies
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -eu
      jam update-dependencies \
        --buildpack-file "${PWD}/buildpack.toml" \
