name: 'Update buildpack.toml with new dependencies'

description: |
  This action updates the buildpack.toml with any new dependency versions.

outputs:
  new-versions:
    description: Newly added dependency versions
    value: ${{ steps.update.outputs.new_versions }}

runs:
  using: 'composite'
  steps:

  - name: Choose Jam Version
    id: version
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      version=$(jq -r .jam "scripts/.util/tools.json")
      echo "version=${version#v}" >> "$GITHUB_OUTPUT"

  - name: Install Jam
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      mkdir -p "${HOME}"/bin
      echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
      mkdir -p "${HOME}/bin"
      curl "https://github.com/paketo-buildpacks/jam/releases/download/v${{ steps.version.outputs.version }}/jam-linux" \
        --fail-with-body \
        --show-error \
        --silent \
        --location \
        --output "${HOME}/bin/jam"
      chmod +x "${HOME}/bin/jam"

  - name: Update Dependencies
    shell: bash
    id: update
    run: |
      #!/usr/bin/env bash
      set -euo pipefail
      shopt -s inherit_errexit
      versions="$(
        jam update-dependencies \
          --buildpack-file "${PWD}/buildpack.toml"
      )"
      versions="$(echo ${versions} | cut -d'[' -f2- | cut -d']' -f-1 | sed 's/ /, /g')"
      echo "new_versions=${versions}" >> "$GITHUB_OUTPUT"
