name: 'Open Pull Request'

description: |
  Opens a Pull Request

inputs:
  token:
    description: 'Token used to authenticate user account'
    required: true
  title:
    description: 'Title given to the PR'
    required: true
  body:
    description: 'Body of the PR'
    default: ''
  branch:
    description: 'Branch to PR'
    required: true
  base:
    description: 'Branch into which the code should be merged'
    default: 'main'
  label:
    description: 'Optional label to add to the PR. Note: Label must already be created on the repository.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--token"
  - ${{ inputs.token }}
  - "--title"
  - ${{ inputs.title }}
  - "--body"
  - ${{ inputs.body }}
  - "--branch"
  - ${{ inputs.branch }}
  - "--base"
  - ${{ inputs.base }}
  - "--label"
  - ${{ inputs.label }}
