name: 'Checkout branch'

description: |
  Checkout a branch at a specified start point.
  If no start point is provided, then checkout the upstream equivalent of the provided branch.
  If the branch doesn't exist on the upstream, create it at the HEAD.

inputs:
  branch:
    description: 'Name of the branch to checkout'
    required: true
  start-point:
    description: 'Reference to checkout the branch at. If not provided, will default to the upstream if it exists or HEAD if there is no equivalent upstream branch.'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--branch"
  - ${{ inputs.branch }}
  - "--start-point"
  - ${{ inputs.start-point }}
