#!/bin/bash

set -eu
set -o pipefail

function main() {
  local branch
  while [ "${#}" != 0 ]; do
    case "${1}" in
      --branch)
        branch="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  git fetch origin
  if git branch -a | grep "${branch}"; then
    git checkout -b "${branch}" "origin/${branch}"
    git pull -r
    chmod -R a+w .
  else
    git checkout -b "${branch}"
  fi
}

main "${@:-}"
