#!/bin/bash
set -euo pipefail
shopt -s inherit_errexit

function main() {
  local branch start_point
  while [ "${#}" != 0 ]; do
    case "${1}" in
      --branch)
        branch="${2}"
        shift 2
        ;;

      --start-point)
        start_point="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  git config --global --add safe.directory "${GITHUB_WORKSPACE}"
  git fetch origin

  if [[ -n "${start_point}" ]]; then
    git checkout -b "${branch}" "${start_point}"
  else
    if git branch -a | grep "${branch}"; then
      git checkout -b "${branch}" "origin/${branch}"
      git pull -r
      chmod -R a+w .
    else
      git checkout -b "${branch}"
    fi
  fi
}

main "${@:-}"
