name: 'Create Language Family Release Notes'

description: |
  Creates release notes for a language family

runs:
  using: 'docker'
  image: 'Dockerfile'

outputs:
  release_body:
    description: Generated detailed release notes for the language family
