name: 'Rebase PR'

description: |
  Rebases a PR against the base branch

inputs:
  user:
    description: 'User account to use when approving'
    required: true
  token:
    description: 'Token used to authenticate user account'
    required: true
  number:
    description: 'PR number'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--user"
  - ${{ inputs.user }}
  - "--token"
  - ${{ inputs.token }}
  - "--number"
  - ${{ inputs.number }}
