name: 'Rebase PR'

description: |
  Rebases a PR against the base branch

inputs:
  token:
    description: 'Token used to authenticate user account'
    required: true
  number:
    description: 'PR number'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--token"
  - ${{ inputs.token }}
  - "--number"
  - ${{ inputs.number }}
