#!/bin/bash

set -eu
set -o pipefail

function main() {
  local token number

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --token)
        token="${2}"
        shift 2
        ;;

      --number)
        number="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  echo "${token}" | gh auth login --with-token

  echo "Rebasing PR ${number}"

  git config --global --add safe.directory "${GITHUB_WORKSPACE}"
  pushd "${GITHUB_WORKSPACE}" > /dev/null || true
    gh api "repos/${GITHUB_REPOSITORY}/pulls/${number}/update-branch" \
      -X PUT \
      -H "Accept: application/vnd.github.lydian-preview+json"
  popd > /dev/null || true
}

main "${@:-}"
