#!/bin/bash

set -eu
set -o pipefail

function main() {
  local token number

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --token)
        token="${2}"
        shift 2
        ;;

      --number)
        number="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  echo "${token}" | gh auth login --with-token

  echo "Merging PR ${number}"

  pushd "${GITHUB_WORKSPACE}" > /dev/null || true
    gh pr merge "${number}" --rebase --delete-branch=false
  popd > /dev/null || true
}

main "${@:-}"
