name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@c314dda4a9a93b08239ec978f2043b9a433b9ac4 # v46.3.0
      env:
        RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}
      with:
        configurationFile: ./.github/renovate-config.js
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
