---
name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.17.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check repo structure
      run: ./scripts/sanity.sh
    - name: Run Unit Tests
      run: ./scripts/unit.sh
