---
name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.x
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check repo structure
      run: ./scripts/sanity.sh
    - name: Run Unit Tests
      run: ./scripts/unit.sh

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-22.04
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: event-payload
        path: ${{ github.event_path }}
