name: 'Dispatch'

description: |
  This action can be used to send a generic repository_dispatch event to a set
  of repos. This is useful when you want to send info from one repository to
  others through an action. For example, we use this action to notify
  language-family repos when their implementation dependencies get updates.

inputs:
  repos:
    description: 'Comma-separated list of repositories that should receive the dispatch event'
    required: true
  token:
    description: 'Github Access Token used to make the request'
    required: true
  event:
    description: 'Event type sent with the dispatch'
    required: true
  payload:
    description: 'Payload sent with the dispatch'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "--repos"
  - ${{ inputs.repos }}
  - "--token"
  - ${{ inputs.token }}
  - "--event"
  - ${{ inputs.event }}
  - "--payload"
  - ${{ inputs.payload }}
